### ISSUE TITLE
Unable to get configuration value from config server.

### ISSUE THREAD

**Issue by rahiakela** [PacktPublishing/Mastering-Microservices-with-Java-Third-Edition#1]
Hi,

I am following your code base and do everything as it is.
 But I am not able to get value from config server, it give default value always.

@Value("${app.greet.msg}")   String message;

I did not change anything. Please help me.

**Comment by sharmasourabh** [comment]
Hi @rahiakela ,
Please make sure the config server is up and running before starting any domain service. Also, make sure config server configuration are correct in domain service's application/bootstrap.yaml.

Please share logs if you face issue even after making above checks.
