### ISSUE TITLE
Chapter 4 root POM.xml error

### ISSUE THREAD

**Issue by sandeep-sparrow** [PacktPublishing/Mastering-Microservices-with-Java-Third-Edition#18]
<executable>${JAVA_1_11_HOME}/bin/javac</executable> -> is not defined or not found.
<img width="630" alt="image" src="https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/61901052/fb90c115-c774-4531-8e03-38bfbb73b8c8">
 
can you please help, what is the purpose of it and how to resolve the error. I think it is path for java compiler but where it's added to this place and with this specific syntax.

**Comment by sharmasourabh** [comment]
IntelliJ complains about it because it could not find the property in pom.xml.

You can either set it pom.xml in properties as shown below:

```xml
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>1.11</java.version>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <JAVA_1_11_HOME>/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home</JAVA_1_11_HOME>
  </properties>
```

Or, add it maven's settings.xml:

```xml
 <profile>
    <id>compiler</id>
    <properties>
      <JAVA_1_11_HOME>/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home</JAVA_1_11_HOME>
    </properties>
 </profile>
```    

For more information, you can visit: 
https://maven.apache.org/plugins/maven-compiler-plugin/examples/compile-using-different-jdk.html

**Comment by sandeep-sparrow** [comment]
thanks, i added the property in the POM.xml with the path location pointing to Javac
