### ISSUE TITLE
docker-assembly.xml - restuarant-service - error - URI is missing or not found

### ISSUE THREAD

**Issue by sandeep-sparrow** [PacktPublishing/Mastering-Microservices-with-Java-Third-Edition#19]
<img width="634" alt="image" src="https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/61901052/c167cbdd-2478-46f6-89c7-7e0e33c9c534">

**Comment by sharmasourabh** [comment]
URLs have been changed. Check the next image for comparison:
![image](https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/20105607/e8d0713a-b55e-43e4-a259-0bd23f68e9ad)

Action:
1.  You can replace `http://www.w3.org/2001/XMLSchemainstance` with `http://www.w3.org/2001/XMLSchema-instance`.
2. Replace `http://maven.apache.org/plugins/maven-assemblyplugin/assembly/1.1.2` with `http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2`
3. From error dialogs (as shown on image you added) on `http://maven.apache.org/xsd/assembly-1.1.2.xsd` and `http://www.w3.org/2001/XMLSchema-instance`, click on `more actions...`, then click on `Fetch external resource` as shown in next image to resolve the issue.

![image](https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/20105607/e7858ba5-1090-43ba-8f85-7e182b4d180e)

**Comment by sandeep-sparrow** [comment]
Thanks!

**Comment by sandeep-sparrow** [comment]
keeping the issue open for reference purpose
