### ISSUE TITLE
Not able to call APIs after configuring Oauth2

### ISSUE THREAD

**Issue by rahiakela** [PacktPublishing/Mastering-Microservices-with-Java-Third-Edition#2]
Hi,

I am using Spring Boot 2.1.7.RELEASE and Spring Cloud Greenwich.SR2.

Problem: 
I am able to generate access token using:-
         1-Resource owner password credential grant
         2-Client credentials grant
But not using these grant type:-
         1-Authorization code grant
         2-Implicit grant

Security-Service configuration:
   application.yml
![app1](https://user-images.githubusercontent.com/2600463/66106892-9791ee80-e5dc-11e9-8a01-8d89e18b6ca9.JPG)

Zuul-API-Gateway configuration:
  application.yml
  
![app2](https://user-images.githubusercontent.com/2600463/66107042-f2c3e100-e5dc-11e9-9717-9d85998db0e4.JPG)

And the configuration and coding are same as your guideline but I am getting this error while using these grant type:
   1-Resource owner password credential grant
   2-Client credentials grant

![post1](https://user-images.githubusercontent.com/2600463/66107197-47675c00-e5dd-11e9-8b4c-89dd3f47d291.JPG)

Now if i call any API then getting this error:
![post2](https://user-images.githubusercontent.com/2600463/66107399-d1afc000-e5dd-11e9-891e-e03ecfcc6d51.JPG)

And these are the log files of sercurity-service and zuul-api-gateway:
   1-security-service.log file:
[security-service.log](https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/files/3684953/security-service.log)
   2-zuul-api-gateway.log file: 
[zuul-api-gateway.log](https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/files/3684955/zuul-api-gateway.log)

Please let me know what are missing in this configuration.
Thanks
Rahi

**Comment by sharmasourabh** [comment]
Configuration looks good to me. Could you please share your code repo that I can access and replicate the issue?

PS: I hope you are using the same access token generated by `/oauth/token` while making the call to `/v1/restaurants/` endpoint. Because I could see access token **3a3***** is received from `/oauth/token` , whereas some different access token **d122***** is used in `/v1/restaurants` call. Please ignore if `/v1/restaurants` request token is valid.

**Comment by rahiakela** [comment]
Hi Sourabh,

Token is valid, actually I have taken the screen-shot before generating it.

And this is code base [URL:](https://github.com/rahiakela/spring-microservices-projects/tree/otrs-microservice/otrs-microservice/section-2-microservice-patterns)

Thanks
Rahi
And
