### ISSUE TITLE
mvn docker:build is failing

### ISSUE THREAD

**Issue by sandeep-sparrow** [PacktPublishing/Mastering-Microservices-with-Java-Third-Edition#20]
could you please guide.

<img width="956" alt="image" src="https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/61901052/06f833cb-e903-4ec1-b6ba-6e0dbc81d47d">

**Comment by sandeep-sparrow** [comment]
I am trying to build this on windows platform.

**Comment by sharmasourabh** [comment]
It looks like either the docker is not installed properly,or the shell you are running the maven build can't recognise the docker environment.

You may want to execute the following command in same shell you are running the build: `eval "$(docker-machine env default)"` if docker is installed properly.
Then, try running the build again.

**Comment by sandeep-sparrow** [comment]
$ eval $(docker-machine env default)
bash: docker-machine: command not found

i am getting this response

**Comment by sharmasourabh** [comment]
It means you must be using the latest Docker. `docker-machine` is deprecated in 2021.

Are you able to run any docker container locally and still facing issue while running the build in same shell? If you have installed Docker recently, you may want to restart your machine if you haven't.

**Comment by sandeep-sparrow** [comment]
yes, docker got installed a fresh update, i will restart and let your know. Thanks again.

**Comment by sandeep-sparrow** [comment]
the retstart did not help

**Comment by sharmasourabh** [comment]
Did you try running any container in same shell and did it work? Could you please post the output with command here?

Also, did you set the DOCKER_HOST variable with correct daemon path?

**Comment by sandeep-sparrow** [comment]
I am trying to run with a direct Dockerfile present in class path of another project and see if it works.

**Comment by sandeep-sparrow** [comment]
SS of docker file

<img width="243" alt="image" src="https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/61901052/8283ccac-c899-4720-b96f-58dab153047f">

contents of Dockerfile

`#Start with a base image containing Java runtime
FROM openjdk:17-slim as build

MAINTAINER eazybytes.com

# Add the application's jar to the container
COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

# Execute the application
ENTRYPOINT ["java","-jar","/accounts-0.0.1-SNAPSHOT.jar"]`

Step1: created docker image cmd: docker build . -t eazybytes/accounts

docker image created successfully 

<img width="960" alt="image" src="https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/61901052/110491ca-a45e-40c7-96a9-7886a6b70e12">

Step2: run docker image in container, cmd: docker run -p 8080:8080 eazybytes/accounts

docker container runs success in this case

**Comment by sandeep-sparrow** [comment]
<img width="955" alt="image" src="https://github.com/PacktPublishing/Mastering-Microservices-with-Java-Third-Edition/assets/61901052/59dc759c-a515-4558-94d0-589558e191d1">

when running the mvn docker:build command for dynamic creation of DockerFile, following error is encountered.

`[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.9:build (default-cli) on project restaurant-service: Execution default-cli of goal org.jolokia:docker-maven-plugin:0.13.9:build failed: No url given, no DOCKER_HOST environment variable and no read/writable '/var/run/docker.sock' -> [Help 1]
`

**Comment by sharmasourabh** [comment]
It seems, plugin `docker-maven-plugin`'s version (`0.13.9`) doesn't support the latest Docker. You may want to update the plugin.

Latest version can be found at https://github.com/fabric8io/docker-maven-plugin, you may want to refer its user manual for the changes.

**Comment by sandeep-sparrow** [comment]
`


        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.43.0</version>`

using abvoe plugin worked fine with the latest docker version

**Comment by sandeep-sparrow** [comment]
@sharmasourabh can you please add me as collab on dev branch will checkin the latest maven-docker-plugin for user's having latest docker version installed on their system.
